// import { generateClient } from 'aws-amplify/data';
// import { type Schema } from '@/amplify/data/resource';
// import outputs from '@/amplify_outputs.json';
// import { Amplify } from 'aws-amplify';

// Amplify.configure(outputs);

// const client = generateClient<Schema>();

// const trees: {
//   variety: string;
//   rootstock: string;
//   scionwood: string;
//   yearPlanted: number;
//   row: number;
//   column: number;
//   status: string;
// }[] = [
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M9',
//     scionwood: 'Gala',
//     yearPlanted: 2020,
//     row: 1,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 2,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 3,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 4,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 5,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 6,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 7,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 8,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 9,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 10,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 11,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 12,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 13,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 14,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 15,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 16,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 17,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 18,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 19,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 20,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 21,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cox Orange Pippin',
//     rootstock: 'M26',
//     scionwood: 'Cox Orange Pippin',
//     yearPlanted: 2021,
//     row: 22,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 23,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 24,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 25,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 26,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 27,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 28,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 29,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 30,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 31,
//     column: 1,
//     status: 'healthy',
//   },
//   {
//     variety: 'Virginia Hewes Crab',
//     rootstock: 'M26',
//     scionwood: 'Virginia Hewes Crab',
//     yearPlanted: 2021,
//     row: 32,
//     column: 1,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 2
//   //
//   //
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 1,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 2,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 3,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 4,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 5,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 6,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 7,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 8,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 9,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 10,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 11,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 12,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 13,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 14,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 15,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 16,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 17,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 18,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 19,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 20,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 21,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 22,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 23,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 24,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 25,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 26,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 27,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 28,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 29,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Oxford Black',
//     rootstock: 'M7',
//     scionwood: 'Oxford Black',
//     yearPlanted: 2021,
//     row: 30,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Chisel Jersey',
//     rootstock: 'M7',
//     scionwood: 'Chisel Jersey',
//     yearPlanted: 2021,
//     row: 31,
//     column: 2,
//     status: 'healthy',
//   },
//   {
//     variety: 'Chisel Jersey',
//     rootstock: 'M7',
//     scionwood: 'Chisel Jersey',
//     yearPlanted: 2021,
//     row: 32,
//     column: 2,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 3
//   //
//   //

//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 1,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 2,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 3,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 4,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 5,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Yarlington Mill',
//     rootstock: 'MM106',
//     scionwood: 'Yarlington Mill',
//     yearPlanted: 2021,
//     row: 6,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 7,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 8,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 9,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 10,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 11,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Arkansas Black',
//     rootstock: 'M7',
//     scionwood: 'Arkansas Black',
//     yearPlanted: 2021,
//     row: 12,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 13,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 14,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 15,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 16,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 17,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 18,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 19,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 20,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 21,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 22,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 24,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 25,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 26,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 27,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 28,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 29,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 30,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 31,
//     column: 3,
//     status: 'healthy',
//   },
//   {
//     variety: 'Golden Russet',
//     rootstock: 'M7',
//     scionwood: 'Golden Russet',
//     yearPlanted: 2021,
//     row: 32,
//     column: 3,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 5
//   //
//   //
//   {
//     variety: 'Unknown',
//     rootstock: 'M7',
//     scionwood: 'Unknown',
//     yearPlanted: 2021,
//     row: 1,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Unknown',
//     rootstock: 'M7',
//     scionwood: 'Unknown',
//     yearPlanted: 2021,
//     row: 2,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Braeburn',
//     rootstock: 'M7',
//     scionwood: 'Braeburn',
//     yearPlanted: 2021,
//     row: 3,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Braeburn',
//     rootstock: 'M7',
//     scionwood: 'Braeburn',
//     yearPlanted: 2021,
//     row: 4,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Whitney Crab',
//     rootstock: 'M7',
//     scionwood: 'Whitney Crab',
//     yearPlanted: 2021,
//     row: 5,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Amere de Berthcourt',
//     rootstock: 'M7',
//     scionwood: 'Amere de Berthcourt',
//     yearPlanted: 2021,
//     row: 6,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harry Masters Jersey',
//     rootstock: 'M7',
//     scionwood: 'Harry Masters Jersey',
//     yearPlanted: 2021,
//     row: 7,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harry Masters Jersey',
//     rootstock: 'M7',
//     scionwood: 'Harry Masters Jersey',
//     yearPlanted: 2021,
//     row: 8,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Ashmead\'s Kernel',
//     rootstock: 'M7',
//     scionwood: 'Ashmead\'s Kernel',
//     yearPlanted: 2021,
//     row: 9,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Ashmead\'s Kernel',
//     rootstock: 'M7',
//     scionwood: 'Ashmead\'s Kernel',
//     yearPlanted: 2021,
//     row: 10,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Cimetere',
//     rootstock: 'M7',
//     scionwood: 'Cimetere',
//     yearPlanted: 2021,
//     row: 11,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Michelin',
//     rootstock: 'M7',
//     scionwood: 'Michelin',
//     yearPlanted: 2021,
//     row: 12,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Michelin',
//     rootstock: 'M7',
//     scionwood: 'Michelin',
//     yearPlanted: 2021,
//     row: 13,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Tremlett\'s Bitter',
//     rootstock: 'M7',
//     scionwood: 'Tremlett\'s Bitter',
//     yearPlanted: 2021,
//     row: 14,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Sweet Choppin',
//     rootstock: 'M7',
//     scionwood: 'Sweet Choppin',
//     yearPlanted: 2021,
//     row: 15,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Sweet Choppin',
//     rootstock: 'M7',
//     scionwood: 'Sweet Choppin',
//     yearPlanted: 2021,
//     row: 16,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Tompkins King',
//     rootstock: 'M7',
//     scionwood: 'Tompkins King',
//     yearPlanted: 2021,
//     row: 17,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Tompkins King',
//     rootstock: 'M7',
//     scionwood: 'Tompkins King',
//     yearPlanted: 2021,
//     row: 18,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: '***',
//     rootstock: 'M7',
//     scionwood: '***',
//     yearPlanted: 2021,
//     row: 19,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Lambrook Pippin',
//     rootstock: 'M7',
//     scionwood: 'Lambrook Pippin',
//     yearPlanted: 2021,
//     row: 20,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Belle de Jardin',
//     rootstock: 'M7',
//     scionwood: 'Belle de Jardin',
//     yearPlanted: 2021,
//     row: 21,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Belle de Jardin',
//     rootstock: 'M7',
//     scionwood: 'Belle de Jardin',
//     yearPlanted: 2021,
//     row: 22,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Champlain',
//     rootstock: 'M7',
//     scionwood: 'Champlain',
//     yearPlanted: 2021,
//     row: 23,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Champlain',
//     rootstock: 'M7',
//     scionwood: 'Champlain',
//     yearPlanted: 2021,
//     row: 24,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Nehou',
//     rootstock: 'M7',
//     scionwood: 'Nehou',
//     yearPlanted: 2021,
//     row: 25,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Nehou',
//     rootstock: 'M7',
//     scionwood: 'Nehou',
//     yearPlanted: 2021,
//     row: 26,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Red Vein Crab',
//     rootstock: 'M7',
//     scionwood: 'Red Vein Crab',
//     yearPlanted: 2021,
//     row: 27,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Red Vein Crab',
//     rootstock: 'M7',
//     scionwood: 'Red Vein Crab',
//     yearPlanted: 2021,
//     row: 28,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Redfield',
//     rootstock: 'M7',
//     scionwood: 'Redfield',
//     yearPlanted: 2021,
//     row: 29,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Redfield',
//     rootstock: 'M7',
//     scionwood: 'Redfield',
//     yearPlanted: 2021,
//     row: 30,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Isle of Wight',
//     rootstock: 'M7',
//     scionwood: 'Isle of Wight',
//     yearPlanted: 2021,
//     row: 31,
//     column: 5,
//     status: 'healthy',
//   },
//   {
//     variety: 'Isle of Wight',
//     rootstock: 'M7',
//     scionwood: 'Isle of Wight',
//     yearPlanted: 2021,
//     row: 32,
//     column: 5,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 6
//   //
//   //
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 1,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 2,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 3,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 4,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 5,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 6,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 7,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 8,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 9,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 10,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 11,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 12,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 13,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 14,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 15,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 16,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 17,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 18,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 19,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 20,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 21,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 22,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 23,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 24,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 25,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 26,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 27,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 28,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 29,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 30,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 31,
//     column: 6,
//     status: 'healthy',
//   },
//   {
//     variety: 'Stoke Red',
//     rootstock: 'M7',
//     scionwood: 'Stoke Red',
//     yearPlanted: 2021,
//     row: 32,
//     column: 6,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 7
//   //
//   //
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 1,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 2,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 3,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 4,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 5,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 6,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 7,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 8,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 9,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 10,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 11,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 12,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 13,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 14,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 15,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 16,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 17,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 18,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 19,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 20,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 21,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 22,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 23,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 24,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 25,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 26,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 27,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 28,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 29,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 30,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 31,
//     column: 7,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'M7',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 32,
//     column: 7,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 8
//   //
//   //
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 1,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 2,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 3,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 4,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 5,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 6,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 7,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 8,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 9,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 10,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 11,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 12,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 13,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 14,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 15,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 16,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 17,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 18,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 19,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 20,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 21,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 22,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 23,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 24,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 25,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 26,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 27,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 28,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 29,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 30,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 31,
//     column: 8,
//     status: 'healthy',
//   },
//   {
//     variety: 'Dabinette',
//     rootstock: 'G-935',
//     scionwood: 'Dabinette',
//     yearPlanted: 2021,
//     row: 32,
//     column: 8,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 9
//   //
//   //
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 1,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 2,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 3,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 4,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 5,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 6,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 7,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 8,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 9,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 10,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 11,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 12,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 13,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 14,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 15,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 16,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 17,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 18,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 19,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 20,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 21,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 22,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 23,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 24,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 25,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 26,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 27,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 28,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 29,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 30,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 31,
//     column: 9,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 32,
//     column: 9,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 10
//   //
//   //
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 1,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 2,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 3,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 4,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 5,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 6,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 7,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 8,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 9,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 10,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 11,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 12,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 13,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 14,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 15,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 16,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 17,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 18,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 19,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 20,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 21,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 22,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 23,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 24,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 25,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 26,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 27,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 28,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 29,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 30,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 31,
//     column: 10,
//     status: 'healthy',
//   },
//   {
//     variety: 'Harrison',
//     rootstock: 'G-935',
//     scionwood: 'Harrison',
//     yearPlanted: 2021,
//     row: 32,
//     column: 10,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 11
//   //
//   //
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 1,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 2,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 3,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 4,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 5,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 6,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 7,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 8,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 9,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 10,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 11,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 12,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 13,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 14,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 15,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 16,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 17,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 18,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 19,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 20,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 21,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 22,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 23,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 24,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 25,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 26,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 27,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 28,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 29,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 30,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 31,
//     column: 11,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 32,
//     column: 11,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 12
//   //
//   //
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 1,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 2,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 3,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 4,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 5,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 6,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 7,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 8,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 9,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 10,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 11,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 12,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 13,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 14,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 15,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 16,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 17,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 18,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 19,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 20,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 21,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 22,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 23,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 24,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 25,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 26,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 27,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 28,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 29,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 30,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 31,
//     column: 12,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 32,
//     column: 12,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 13
//   //
//   //
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 1,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 2,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 3,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 4,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 5,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 6,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 7,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 8,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 9,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 10,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 11,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 12,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 13,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 14,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 15,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 16,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 17,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 18,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 19,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 20,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 21,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 22,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 23,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 24,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 25,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 26,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 27,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 28,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 29,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 30,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 31,
//     column: 13,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 32,
//     column: 13,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 14
//   //
//   //
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 1,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 2,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 3,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 4,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 5,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 6,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 7,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 8,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 9,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 10,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 11,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 12,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 13,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 14,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 15,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 16,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 17,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 18,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 19,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 20,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 21,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 22,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 23,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 24,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 25,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 26,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 27,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 28,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 29,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 30,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 31,
//     column: 14,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 32,
//     column: 14,
//     status: 'healthy',
//   },
//   //
//   //
//   //COLUMN 15
//   //
//   //
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 1,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 2,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 3,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 4,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 5,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 6,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 7,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 8,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Brown Snout',
//     rootstock: 'G-935',
//     scionwood: 'Brown Snout',
//     yearPlanted: 2021,
//     row: 9,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 10,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 11,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Kingston Black',
//     rootstock: 'G-935',
//     scionwood: 'Kingston Black',
//     yearPlanted: 2021,
//     row: 12,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 13,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 14,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 15,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 16,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 17,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 18,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 19,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 20,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 21,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Puget Spice',
//     rootstock: 'G-935',
//     scionwood: 'Puget Spice',
//     yearPlanted: 2021,
//     row: 22,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 23,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 24,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 25,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 26,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 27,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 28,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 29,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 30,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 31,
//     column: 15,
//     status: 'healthy',
//   },
//   {
//     variety: 'Antonovka',
//     rootstock: 'G-935',
//     scionwood: 'Antonovka',
//     yearPlanted: 2021,
//     row: 32,
//     column: 15,
//     status: 'healthy',
//   },

//   // Add more trees here...
// ].map(tree => {
//     if (['Kingston Black', 'Harrison', 'Brown Snout', 'Stoke Red'].includes(tree.variety)) {
//       return { ...tree, rootstock: 'G-890' };
//     }
//     if (['Cox Orange Pippin', 'Virginia Crab', 'Northern Spy', 'Muscat de Bernay', 'Yarlington Mill', 'Arkansas Black', 'Golden Russet'].includes(tree.variety)) {
//       return { ...tree, rootstock: 'M-111' };
//     }
//     return tree;
//   });
  

// async function importTrees() {
//   for (const tree of trees) {
//     try {
//       await client.models.Tree.create({
//         variety: tree.variety,
//         rootstock: tree.rootstock,
//         scionwood: tree.scionwood,
//         yearPlanted: tree.yearPlanted,
//         row: tree.row,
//         column: tree.column,
//       });
//       console.log(`Inserted tree: ${tree.variety} at row ${tree.row}, column ${tree.column}`);
//     } catch (error) {
//       console.error(`Error inserting tree: ${error}`);
//     }
//   }
// }

// importTrees();